server:
  port: 9090

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    platform: postgres
    hikari:
      maximum-pool-size: 4

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  token.expired-time-ms: 2592000000  # 30 days